 CREATE TABLE "SAI_ROLES" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"SLUG" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"PERMISSIONS" VARCHAR2(255 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT NULL, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT NULL, 
	 CONSTRAINT "PK_SAI_ROLES" PRIMARY KEY ("ID")
	);


 CREATE TABLE "SAI_USUARIOS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(255 BYTE) DEFAULT NULL, 
	"LAST_NAME" VARCHAR2(255 BYTE) DEFAULT NULL, 
	"PASSWORD" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"PERMISSIONS" VARCHAR2(255 BYTE), 
	"LAST_LOGIN" TIMESTAMP (6), 
	"NUM_LOGIN" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT NULL, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT NULL, 
	"IS_ACTIVE" NUMBER(*,0) DEFAULT 1, 
	"IS_SUPERADMIN" NUMBER(*,0), 
	"IS_STAFF" NUMBER(*,0), 
	"ROL_ID" NUMBER(*,0), 
	 CONSTRAINT "PK_SAI_USUARIOS" PRIMARY KEY ("ID"), 
	 CONSTRAINT "UQ_EMAIL" UNIQUE ("EMAIL")
	);
