CREATE TABLE SAI_PARTICIPANTE (
  id int NOT NULL ,
  report_id int NOT NULL,
  ambito_id int not null,
  pais_id int not null,
  entidad VARCHAR(150) null,
  otro_id int,
  rol_id int ,
  CONSTRAINT PK_SAI_PARTICIPANTE_ID PRIMARY KEY (id),
  CONSTRAINT FK_SAI_AUDITORIA_PARTI_ID FOREIGN KEY (REPORT_id) REFERENCES SAI_AUDITORIA(ID),
  CONSTRAINT FK_SAI_AMBITO_ID FOREIGN KEY (AMBITO_id) REFERENCES SAI_AMBITO(ID),
  CONSTRAINT FK_SAI_PAIS_ID FOREIGN KEY (PAIS_id) REFERENCES SAI_PAIS(ID)
);


CREATE TABLE SAI_INFORME(
  id int NOT NULL ,
  report_id int NOT NULL,
  informe_id int,
  fecha_publicacion timestamp,
  pais_id int,
  idioma_id int,
  archivo varchar(150),
  url_video varchar(250),
  CONSTRAINT PK_SAI_INFORME_ID PRIMARY KEY (id),
  CONSTRAINT FK_SAI_AUDITORIA_INFO_ID FOREIGN KEY (REPORT_id) REFERENCES SAI_AUDITORIA(ID),
  CONSTRAINT FK_SAI_INFO_PAIS_ID FOREIGN KEY (PAIS_id) REFERENCES SAI_PAIS(ID),
  CONSTRAINT FK_SAI_IDIOMA_ID FOREIGN KEY (IDIOMA_id) REFERENCES SAI_IDIOMA(ID)
);




CREATE TABLE SAI_PRACTICA(
  id int NOT NULL ,
  report_id int NOT NULL,
  titulo varchar(100),
  etapa varchar(100),
  contexto varchar(100),
  descripcion varchar(250),
  activo char(1) DEFAULT 'N' NOT NULL,
  CONSTRAINT PK_SAI_PRACTICA_ID PRIMARY KEY (id),
  CONSTRAINT FK_SAI_AUDITORIA_PRAC_ID FOREIGN KEY (REPORT_id) REFERENCES SAI_AUDITORIA(ID)
);