CREATE SEQUENCE  "SEQ_SAI_AUDITORIA_ODS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 87 CACHE 20 NOORDER  NOCYCLE ;

CREATE OR REPLACE TRIGGER "SAI_AUDITORIA_ODS_BIR" 
BEFORE INSERT ON SAI_AUDITORIA_ODS 
FOR EACH ROW
BEGIN
  SELECT SEQ_SAI_AUDITORIA_ODS.NEXTVAL INTO :new.ID FROM dual;
END;
/
ALTER TRIGGER "SAI_AUDITORIA_ODS_BIR" ENABLE;

CREATE SEQUENCE  "SEQ_SAI_AUDITORIA_MOSCU"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE OR REPLACE TRIGGER "SAI_AUDITORIA_MOSCU_BIR" 
BEFORE INSERT ON SAI_AUDITORIA_MOSCU 
FOR EACH ROW
BEGIN
  SELECT SEQ_SAI_AUDITORIA_MOSCU.NEXTVAL INTO :new.ID FROM dual;
END;
/
ALTER TRIGGER "SAI_AUDITORIA_MOSCU_BIR" ENABLE;

CREATE SEQUENCE  "SEQ_SAI_AUDITORIA_TAG"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 289 CACHE 20 NOORDER  NOCYCLE ;

CREATE OR REPLACE TRIGGER "SAI_AUDITORIA_TAG_BIR" 
BEFORE INSERT ON SAI_AUDITORIA_TAG 
FOR EACH ROW
BEGIN
  SELECT SEQ_SAI_AUDITORIA_TAG.NEXTVAL INTO :new.ID FROM dual;
END;
/
ALTER TRIGGER "SAI_AUDITORIA_TAG_BIR" ENABLE;
