INSERT INTO SAI_PARAMETRO (ID,TABLE_NAME, CODE, VALUE_NAME)VALUES (5,'TABLE_STATUS', 1,'REGISTRADO');
INSERT INTO SAI_PARAMETRO (ID,TABLE_NAME, CODE, VALUE_NAME)VALUES (5,'TABLE_STATUS', 2,'EN PROCESO');
INSERT INTO SAI_PARAMETRO (ID,TABLE_NAME, CODE, VALUE_NAME)VALUES (5,'TABLE_STATUS', 3,'OBSERVADOS');
INSERT INTO SAI_PARAMETRO (ID,TABLE_NAME, CODE, VALUE_NAME)VALUES (5,'TABLE_STATUS', 4,'APROBADO');
COMMIT;