CREATE TABLE SAI_OBSERVACION(
ID INT NOT NULL, 
REPORT_ID INT NOT NULL,
MOTIVO VARCHAR2(100) NOT NULL,
CONSTRAINT PK_SAI_OBSERVACION_ID PRIMARY KEY (ID),
CONSTRAINT FK_SAI_AUDITORIA_OBSE_ID FOREIGN KEY (REPORT_ID) REFERENCES SAI_AUDITORIA(ID)
);

CREATE SEQUENCE  "SEQ_SAI_OBSERVACION"  
MINVALUE 1 
MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE OR REPLACE TRIGGER "SAI_OBSERVACION_BIR" 
BEFORE INSERT ON SAI_OBSERVACION 
FOR EACH ROW
BEGIN
  SELECT SEQ_SAI_OBSERVACION.NEXTVAL INTO :new.ID FROM dual;
END;
