ALTER TABLE SAI_USUARIOS ADD GENERO CHAR(1) CONSTRAINT FK_GENERO CHECK (GENERO IN ('F','M'));

CREATE TABLE SAI_PAISES (
  id int NOT NULL,
  country_id int DEFAULT NULL,
  sai_name varchar(255) NOT NULL,
  sai_slug varchar(255) DEFAULT NULL,
  sai_name_large varchar(255) DEFAULT NULL,
  sai_web varchar(255) DEFAULT NULL,
  sai_enlace varchar(255) DEFAULT NULL,
  group_id int DEFAULT NULL,
  created_at timestamp DEFAULT NULL,
  updated_at timestamp DEFAULT NULL,
  CONSTRAINT "PK_SAI_PAISES" PRIMARY KEY ("ID")
);

ALTER TABLE SAI_USUARIOS ADD PAIS_ID INT;

ALTER TABLE SAI_USUARIOS ADD CONSTRAINT FK_PAIS FOREIGN KEY(PAIS_ID) REFERENCES SAI_PAISES(ID);