 CREATE TABLE "SAI_DECLARACION_MOSCU" 
   (	
   "ID" NUMBER(*,0) NOT NULL ENABLE, 
	"DECLARATION_NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT NULL, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT NULL, 
	 CONSTRAINT "PK_SAI_DECLARACION_MOSCU" PRIMARY KEY ("ID")
  )